### ISSUE TITLE
[SDFormat->MJCF] Support `//world/light` and `//link/light`

### ISSUE THREAD

**Issue by azeey** [gazebosim/gz-mujoco#11]

**Comment by ahcorde** [comment]
` //link//light` PR https://github.com/gazebosim/gz-mujoco/pull/19

**Comment by azeey** [comment]
@ahcorde , #19 only added conversion for `sdformat.Light`. Do we need to add `//link/light` just like `//visual/material` in #34?

**Comment by azeey** [comment]
Closed by #37
