### ISSUE TITLE
conda installation

### ISSUE THREAD

**Issue by wandida** [gazebosim/gz-mujoco#117]
hey, I get the following error by using ```sdf2mjcf ``` with conda
i did ```conda install sdformat-mjcf ``` and then ```sdf2mjcf mug.xml test.sdf``` with the mujoco mug and get:

```

(base) wand_da@rmc-lx0470 ~/git/annikonda_sample/mujoco/whitebert (feat/mujoco)$ sdf2mjcf test_defaults.xml test.sdf
Error:   Could not find the 'robot' element in the xml file
         at line 109 in /home/conda/feedstock_root/build_artifacts/urdfdom_1681364098593/work/urdf_parser/src/model.cpp
Error Code 1: Msg: Unable to read file:test_defaults.xml

(base) wand_da@rmc-lx0470 ~/git/annikonda_sample/mujoco/whitebert (feat/mujoco)$
```

**Comment by traversaro** [comment]
Hello @wandida, can you report the `test_defaults.xml` you are using so that it is possible to reproduce the issue? Could you also report the output of the `conda list` in the environment in which you are experiencing this?

**Comment by wandida** [comment]
well, I'm stupid :)
