### ISSUE TITLE
README questions

### ISSUE THREAD

**Issue by Kakcalu13** [gazebosim/gz-mujoco#17]
Hi there,

I was finally able to put my hands on this gem! I was following the [readme](https://github.com/gazebosim/gz-mujoco/blob/ahcorde/add_primitive_geometry_mesh/sdformat_mjcf/README.md)

I wanted to add new small detials on README, but I need to make sure I understand this first.

I have several questions regarding libsdformat part. 

1) Is `ahcorde/python/all` in sdformat official plugin for this repo? 
2) What is difference between libignition-math7 and ignition-math7? libignition-common5 and igntiion-common5? Cmake couldn't find ignition-math7 and ignition-common5. 

See here
```
-- sdformat13 version 13.0.0~pre1
-- Operating system is Linux
-- Found CPack generators: DEB
-- Checking for module 'tinyxml2'
--   Found tinyxml2, version 6.2.0
-- Looking for TINYXML2 - found

-- Looking for IgnURDFDOM - found

-- Found ruby executable: /usr/bin/ruby
CMake Warning at /usr/share/cmake/ignition-cmake3/cmake3/IgnUtils.cmake:197 (find_package):
  By not providing "Findignition-math7.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "ignition-math7", but CMake did not find one.

  Could not find a package configuration file provided by "ignition-math7"
  with any of the following names:

    ignition-math7Config.cmake
    ignition-math7-config.cmake

  Add the installation prefix of "ignition-math7" to CMAKE_PREFIX_PATH or set
  "ignition-math7_DIR" to a directory containing one of the above files.  If
  "ignition-math7" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:114 (ign_find_package)


-- Looking for ignition-math7 - not found

  Could not find a package configuration file provided by "ignition-common5"
  with any of the following names:

    ignition-common5Config.cmake
    ignition-common5-config.cmake
```

3) I tried to build `libsdformat` folder from the source, but I couldn't due to above.
4) It seems like some requirement needs to be met before able to continue.

I wanted to add more detail for future potential enthusiastic beginners to start with this repo

**Comment by Kakcalu13** [comment]
I can't remove the bug tag. This is more likely documentation

**Comment by azeey** [comment]
> Is ahcorde/python/all in sdformat official plugin for this repo?

That's just a branch we're working on until all the PRs in sdformat are reviewed merged. That branch has all the changes, but has not reviewed.

> What is difference between libignition-math7 and ignition-math7? 

No difference.

> 3, 4

You'll need the nighly repo to install `libignition-math7-dev` and any other dependencies. Follow
http://sdformat.org/tutorials?tut=install&ver=%3E%3D+12&cat=developers&#source-installation except using `deb http://packages.osrfoundation.org/gazebo/ubuntu-nightly` for the repo. Then you should be able to build sdformat.

**Comment by Kakcalu13** [comment]
That worked! 
![image](https://user-images.githubusercontent.com/65916520/168856419-b96480d5-0b7a-40e6-9dea-035d27a5e53a.png)

I will write a readme and PR this week!

**Comment by Kakcalu13** [comment]
Looks like this deletes citadel and fortress everytime I install this.

![image](https://user-images.githubusercontent.com/65916520/168857884-f4102def-3cdf-4798-81b5-e2fe0a5ece4a.png)


This is seperate issue, not related to this project. I guess it's important to mention in the readme
